openapi: 3.0.0
info:
  title: Flask MVC API
  version: 1.0.0
paths:
  /professores/:
    get:
      summary: Lista todos os professores
      responses:
        "200":
          description: OK
    post:
      summary: Cria um professor
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
                disciplina:
                  type: string
      responses:
        "201":
          description: Criado
